include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  rules:
    require_trailing_commas: true
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_types_as_parameter_names: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    eol_at_end_of_file: true
    omit_local_variable_types: true
    avoid_multiple_declarations_per_line: true
    annotate_overrides: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    empty_catches: true
    exhaustive_cases: true

analyzer:
  errors:
    must_be_immutable: ignore
    deprecated_member_use: ignore
    invalid_annotation_target: ignore
  exclude:
    - lib/**/*.g.dart
    - lib/generated/*
    - test/**/*.mocks.dart
